// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: gate_events.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listGateEventsBefore = `-- name: ListGateEventsBefore :many
SELECT id, snapshot_id, round_id, symbol, timestamp,
       global_tradeable, decision_action, grade, gate_reason, direction,
       provider_refs_json, rule_hit_json, derived_json,
       fingerprint, system_config_hash, strategy_config_hash, source_version, created_at
FROM gate_events
WHERE symbol = $1
  AND (created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListGateEventsBeforeParams struct {
	Symbol    string             `db:"symbol" json:"symbol"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ID        int64              `db:"id" json:"id"`
	Limit     int32              `db:"limit" json:"limit"`
}

func (q *Queries) ListGateEventsBefore(ctx context.Context, arg ListGateEventsBeforeParams) ([]GateEvent, error) {
	rows, err := q.db.Query(ctx, listGateEventsBefore,
		arg.Symbol,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GateEvent
	for rows.Next() {
		var i GateEvent
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.RoundID,
			&i.Symbol,
			&i.Timestamp,
			&i.GlobalTradeable,
			&i.DecisionAction,
			&i.Grade,
			&i.GateReason,
			&i.Direction,
			&i.ProviderRefsJson,
			&i.RuleHitJson,
			&i.DerivedJson,
			&i.Fingerprint,
			&i.SystemConfigHash,
			&i.StrategyConfigHash,
			&i.SourceVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGateEventsLatest = `-- name: ListGateEventsLatest :many
SELECT id, snapshot_id, round_id, symbol, timestamp,
       global_tradeable, decision_action, grade, gate_reason, direction,
       provider_refs_json, rule_hit_json, derived_json,
       fingerprint, system_config_hash, strategy_config_hash, source_version, created_at
FROM gate_events
WHERE symbol = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListGateEventsLatestParams struct {
	Symbol string `db:"symbol" json:"symbol"`
	Limit  int32  `db:"limit" json:"limit"`
}

func (q *Queries) ListGateEventsLatest(ctx context.Context, arg ListGateEventsLatestParams) ([]GateEvent, error) {
	rows, err := q.db.Query(ctx, listGateEventsLatest, arg.Symbol, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GateEvent
	for rows.Next() {
		var i GateEvent
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.RoundID,
			&i.Symbol,
			&i.Timestamp,
			&i.GlobalTradeable,
			&i.DecisionAction,
			&i.Grade,
			&i.GateReason,
			&i.Direction,
			&i.ProviderRefsJson,
			&i.RuleHitJson,
			&i.DerivedJson,
			&i.Fingerprint,
			&i.SystemConfigHash,
			&i.StrategyConfigHash,
			&i.SourceVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
