// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: llm_rounds.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findLLMRound = `-- name: FindLLMRound :one
SELECT id, snapshot_id, symbol, round_type, started_at, finished_at,
       total_latency_ms, total_token_in, total_token_out, call_count,
       outcome, prompt_version, error, agent_count, provider_count, gate_action, request_id, created_at
FROM llm_rounds
WHERE id = $1
`

func (q *Queries) FindLLMRound(ctx context.Context, id string) (LlmRound, error) {
	row := q.db.QueryRow(ctx, findLLMRound, id)
	var i LlmRound
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.Symbol,
		&i.RoundType,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TotalLatencyMs,
		&i.TotalTokenIn,
		&i.TotalTokenOut,
		&i.CallCount,
		&i.Outcome,
		&i.PromptVersion,
		&i.Error,
		&i.AgentCount,
		&i.ProviderCount,
		&i.GateAction,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}

const listLLMRoundsBefore = `-- name: ListLLMRoundsBefore :many
SELECT id, snapshot_id, symbol, round_type, started_at, finished_at,
       total_latency_ms, total_token_in, total_token_out, call_count,
       outcome, prompt_version, error, agent_count, provider_count, gate_action, request_id, created_at
FROM llm_rounds
WHERE CASE WHEN $1::text = '' THEN true ELSE symbol = $1 END
  AND (started_at < $2 OR (started_at = $2 AND id < $3))
ORDER BY started_at DESC, id DESC
LIMIT $4
`

type ListLLMRoundsBeforeParams struct {
	Column1   string             `db:"column_1" json:"column_1"`
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
	ID        string             `db:"id" json:"id"`
	Limit     int32              `db:"limit" json:"limit"`
}

func (q *Queries) ListLLMRoundsBefore(ctx context.Context, arg ListLLMRoundsBeforeParams) ([]LlmRound, error) {
	rows, err := q.db.Query(ctx, listLLMRoundsBefore,
		arg.Column1,
		arg.StartedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmRound
	for rows.Next() {
		var i LlmRound
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Symbol,
			&i.RoundType,
			&i.StartedAt,
			&i.FinishedAt,
			&i.TotalLatencyMs,
			&i.TotalTokenIn,
			&i.TotalTokenOut,
			&i.CallCount,
			&i.Outcome,
			&i.PromptVersion,
			&i.Error,
			&i.AgentCount,
			&i.ProviderCount,
			&i.GateAction,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMRoundsLatest = `-- name: ListLLMRoundsLatest :many
SELECT id, snapshot_id, symbol, round_type, started_at, finished_at,
       total_latency_ms, total_token_in, total_token_out, call_count,
       outcome, prompt_version, error, agent_count, provider_count, gate_action, request_id, created_at
FROM llm_rounds
WHERE CASE WHEN $1::text = '' THEN true ELSE symbol = $1 END
ORDER BY started_at DESC, id DESC
LIMIT $2
`

type ListLLMRoundsLatestParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Limit   int32  `db:"limit" json:"limit"`
}

func (q *Queries) ListLLMRoundsLatest(ctx context.Context, arg ListLLMRoundsLatestParams) ([]LlmRound, error) {
	rows, err := q.db.Query(ctx, listLLMRoundsLatest, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmRound
	for rows.Next() {
		var i LlmRound
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Symbol,
			&i.RoundType,
			&i.StartedAt,
			&i.FinishedAt,
			&i.TotalLatencyMs,
			&i.TotalTokenIn,
			&i.TotalTokenOut,
			&i.CallCount,
			&i.Outcome,
			&i.PromptVersion,
			&i.Error,
			&i.AgentCount,
			&i.ProviderCount,
			&i.GateAction,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
