// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GateEvent struct {
	ID                 int64              `db:"id" json:"id"`
	SnapshotID         int64              `db:"snapshot_id" json:"snapshot_id"`
	RoundID            pgtype.Text        `db:"round_id" json:"round_id"`
	Symbol             string             `db:"symbol" json:"symbol"`
	Timestamp          int64              `db:"timestamp" json:"timestamp"`
	GlobalTradeable    bool               `db:"global_tradeable" json:"global_tradeable"`
	DecisionAction     pgtype.Text        `db:"decision_action" json:"decision_action"`
	Grade              int32              `db:"grade" json:"grade"`
	GateReason         pgtype.Text        `db:"gate_reason" json:"gate_reason"`
	Direction          pgtype.Text        `db:"direction" json:"direction"`
	ProviderRefsJson   []byte             `db:"provider_refs_json" json:"provider_refs_json"`
	RuleHitJson        []byte             `db:"rule_hit_json" json:"rule_hit_json"`
	DerivedJson        []byte             `db:"derived_json" json:"derived_json"`
	Fingerprint        pgtype.Text        `db:"fingerprint" json:"fingerprint"`
	SystemConfigHash   pgtype.Text        `db:"system_config_hash" json:"system_config_hash"`
	StrategyConfigHash pgtype.Text        `db:"strategy_config_hash" json:"strategy_config_hash"`
	SourceVersion      pgtype.Text        `db:"source_version" json:"source_version"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type LlmRound struct {
	ID             string             `db:"id" json:"id"`
	SnapshotID     int64              `db:"snapshot_id" json:"snapshot_id"`
	Symbol         string             `db:"symbol" json:"symbol"`
	RoundType      string             `db:"round_type" json:"round_type"`
	StartedAt      pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt     pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	TotalLatencyMs pgtype.Int4        `db:"total_latency_ms" json:"total_latency_ms"`
	TotalTokenIn   pgtype.Int4        `db:"total_token_in" json:"total_token_in"`
	TotalTokenOut  pgtype.Int4        `db:"total_token_out" json:"total_token_out"`
	CallCount      int32              `db:"call_count" json:"call_count"`
	Outcome        pgtype.Text        `db:"outcome" json:"outcome"`
	PromptVersion  string             `db:"prompt_version" json:"prompt_version"`
	Error          pgtype.Text        `db:"error" json:"error"`
	AgentCount     int32              `db:"agent_count" json:"agent_count"`
	ProviderCount  int32              `db:"provider_count" json:"provider_count"`
	GateAction     pgtype.Text        `db:"gate_action" json:"gate_action"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PromptRegistry struct {
	ID           int64              `db:"id" json:"id"`
	Role         string             `db:"role" json:"role"`
	Stage        string             `db:"stage" json:"stage"`
	Version      string             `db:"version" json:"version"`
	SystemPrompt string             `db:"system_prompt" json:"system_prompt"`
	Description  pgtype.Text        `db:"description" json:"description"`
	Active       bool               `db:"active" json:"active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
