// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: prompt_registry.sql

package queries

import (
	"context"
)

const findActivePrompt = `-- name: FindActivePrompt :one
SELECT id, role, stage, locale, version, system_prompt, description, active, created_at, updated_at
FROM prompt_registry
WHERE role = $1 AND stage = $2 AND locale = $3 AND active = true
ORDER BY created_at DESC
LIMIT 1
`

type FindActivePromptParams struct {
	Role   string `db:"role" json:"role"`
	Stage  string `db:"stage" json:"stage"`
	Locale string `db:"locale" json:"locale"`
}

func (q *Queries) FindActivePrompt(ctx context.Context, arg FindActivePromptParams) (PromptRegistry, error) {
	row := q.db.QueryRow(ctx, findActivePrompt, arg.Role, arg.Stage, arg.Locale)
	var i PromptRegistry
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Stage,
		&i.Locale,
		&i.Version,
		&i.SystemPrompt,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPromptEntries = `-- name: ListPromptEntries :many
SELECT id, role, stage, locale, version, system_prompt, description, active, created_at, updated_at
FROM prompt_registry
WHERE CASE WHEN $1::text = '' THEN true ELSE role = $1 END
  AND CASE WHEN $2::boolean THEN active = true ELSE true END
ORDER BY role, stage, locale, created_at DESC
`

type ListPromptEntriesParams struct {
	Role       string `db:"role" json:"role"`
	ActiveOnly bool   `db:"active_only" json:"active_only"`
}

func (q *Queries) ListPromptEntries(ctx context.Context, arg ListPromptEntriesParams) ([]PromptRegistry, error) {
	rows, err := q.db.Query(ctx, listPromptEntries, arg.Role, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptRegistry
	for rows.Next() {
		var i PromptRegistry
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Stage,
			&i.Locale,
			&i.Version,
			&i.SystemPrompt,
			&i.Description,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
