// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"
)

type Querier interface {
	FindActivePrompt(ctx context.Context, arg FindActivePromptParams) (PromptRegistry, error)
	FindLLMRound(ctx context.Context, id string) (LlmRound, error)
	ListGateEventsBefore(ctx context.Context, arg ListGateEventsBeforeParams) ([]GateEvent, error)
	ListGateEventsLatest(ctx context.Context, arg ListGateEventsLatestParams) ([]GateEvent, error)
	ListLLMRoundsBefore(ctx context.Context, arg ListLLMRoundsBeforeParams) ([]LlmRound, error)
	ListLLMRoundsLatest(ctx context.Context, arg ListLLMRoundsLatestParams) ([]LlmRound, error)
	ListPromptEntries(ctx context.Context, arg ListPromptEntriesParams) ([]PromptRegistry, error)
}

var _ Querier = (*Queries)(nil)
