# brale-core 币种清单（由 bralectl init / bralectl add-symbol 维护）
# - symbol: 币种名（必须大写）
# - config: 币种配置文件路径
# - strategy: 币种策略文件路径

#[[symbols]]
#symbol = "SOLUSDT"
#config = "symbols/SOLUSDT.toml"
#strategy = "strategies/SOLUSDT.toml"


[[symbols]]
symbol = "ETHUSDT"
config = "symbols/ETHUSDT.toml"
strategy = "strategies/ETHUSDT.toml"
